welcomemessage:
  check: false
  message: Thanks for opening an issue! Make sure you've followed CONTRIBUTING.md.\n\nWhen you are ready mark the PR ready by commenting `#pr-ready`. If you still have work to do comment with `pr-onhold`.
prcomments:
  check: false
  prreadylabel: pr-ready
  onholdlabel: pr-onhold
prmerge:
  check: false
  labels:
    initiallabel : pr-onhold
    automergelabel : auto-merge
    readytomergelabel : pr-ready
    reviewrequiredlabel : review-required
  mergemethod: merge